os:
  - linux

dist: xenial

language: d

d:
  - ldc
  - dmd

env:
  - ARCH="x86_64"

addons:
  apt:
    packages:
      - libzmq3-dev
      - libopenblas-dev
      - libhdf5-dev

cache: apt

script:
  - dub test --arch "$ARCH" --build=unittest-cov
  - dub build --build=release --config=example-mnist
  - dub build --build=release --config=example-mnist-cnn
  - dub build --build=release --config=example-cifar
  - dub build --build=release --config=example-char-rnn
  - dub build --build=release --config=example-ptb
  # ldc2 causes linker error with drepl https://github.com/dlang-community/drepl/issues/39
  - if [ "$DC" = dmd ]; then
       dub build --build=release --config=repl;
       dub build --build=release --config=jupyterd;
    else
       echo "skipping make repl jupyterd in ${DC}";
    fi
  - cat dub.selections.json

after_success:
  - if [ "$DC" = dmd ]; then
       make doc;
       mv generated-docs docs;
       bash <(curl -s https://codecov.io/bash) -s "source-grain-*.lst";
    else
       echo "skipping coverage and doc stage in ${DC}";
    fi

deploy:
  d: dmd
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
    condition: $DC = dmd

