sudo: false

os:
  - linux

language: d

d:
  - ldc
  - dmd

env:
  - ARCH="x86_64"

addons:
  apt:
    packages:
      - libopenblas-dev
      - libhdf5-dev

cache: apt

script:
  - dub test --arch "$ARCH" --build=unittest-cov

after_success:
  - if [ "$DC" = dmd ]; then
       make doc;
       mv generated-docs docs;
       bash <(curl -s https://codecov.io/bash) -s "source-grain-*.lst";
    else
       echo "skipping coverage and doc stage in ${DC}";
    fi

deploy:
  d: dmd
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
    condition: $DC = dmd

